// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBizbKCQCnbwi8oV9MUIWG3dTYulr95SJc',
    appId: '1:528590894926:web:b7e070daad7c9068c1501f',
    messagingSenderId: '528590894926',
    projectId: 'coffeebeansworld-v1',
    authDomain: 'coffeebeansworld-v1.firebaseapp.com',
    storageBucket: 'coffeebeansworld-v1.firebasestorage.app',
    measurementId: 'G-J31VG8RRML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW8lOgOR9CplEfuhpmtbZXio1rdMZxoEU',
    appId: '1:528590894926:android:17796e451dc29577c1501f',
    messagingSenderId: '528590894926',
    projectId: 'coffeebeansworld-v1',
    storageBucket: 'coffeebeansworld-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQXaQNGuKYLMimm9taUoq00iVQNUbiJK8',
    appId: '1:528590894926:ios:6fc671a762b0e67ec1501f',
    messagingSenderId: '528590894926',
    projectId: 'coffeebeansworld-v1',
    storageBucket: 'coffeebeansworld-v1.firebasestorage.app',
    iosBundleId: 'com.coffeebeansworld.mobile',
    iosClientId:
        '528590894926-akuuodn0so4946spcd85enr0g85g2bcn.apps.googleusercontent.com',
  );
}
